version: "3.9"

services:
  db:
    image: ghcr.io/nestdotland/db:main
    ports: ["5432:5432"]
    env_file: .env
    container_name: nest_db

  gql:
    image: nest_gql_dev
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["4000:4000"]
    env_file: .env
    container_name: nest_gql
    depends_on: ["db"]
